version: "3.8"
services:
  apachephp:
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
      args:
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - DB_HOST=database
    image: apachephp
    container_name: apachephp
    networks:
      - app-295-devops-travel
    ports:
      - 8080:80
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - app-295-devops-travel

networks:
  app-295-devops-travel:
    driver: bridge
