version: "3.8"
services:
  apachephp:
    build:
      context: ./webapp
    image: apachephp
    container_name: apachephp
    networks:
      - app-295-devops-travel
    ports:
      - 8080:80
    depends_on:
      - mariadb
    
  mariadb:
    build:
      context: ./database
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root123
    networks:
      - app-295-devops-travel

networks:
  app-295-devops-travel:
    driver: bridge
