# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20231011.0.0"
  config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/focal64"
  config.vm.box_check_update = true

  config.vm.boot_timeout = 600

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.provision "shell", inline: <<-SHELL
    Repo_Url="https://github.com/RecursiveDeveloper/Reto295DevOps_Exercises.git"

    cd /home/ubuntu
    git clone $Repo_Url
    cd Reto295DevOps_Exercises
    git pull origin main
    chmod -R +x ./Exercise1
    cd Exercise1/
    . ./deploy_LAMP.sh
  SHELL
end
