Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.boot_timeout = 400

  config.vm.synced_folder "./../", "/opt/vagrant"

  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.network "forwarded_port", guest: 5000, host: 5001

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.provision "shell", path: "docker_engine.sh", run: "always"
  # config.vm.provision "shell", inline: <<-SHELL
  #   git clone "https://github.com/RecursiveDeveloper/Reto295DevOps_Exercises.git"
  #   cd Reto295DevOps_Exercises
  #   git pull origin main
  #   chmod -R +x ./Exercise3
  # SHELL
end
