version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: web
    container_name: web
    networks:
      - app-295-devops-travel
    ports:
      - 5000:80
    depends_on:
      - java_api

  java_api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: java_api
    container_name: java_api
    networks:
      - app-295-devops-travel
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-295-devops-travel

networks:
  app-295-devops-travel:
    driver: bridge
