repo_path = "/opt/vagrant/295words-docker"
ngrok_authtoken = "ngrok_authtoken"
ngrok_exposed_port = "5000"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 400

  config.vm.synced_folder "./", "/opt/vagrant"

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8085, host: 8085

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.provision "shell", path: "provisioners/docker_engine.sh"
  config.vm.provision "shell", path: "provisioners/deploy_app.sh",
    args: "#{repo_path}"
  config.vm.provision "shell", path: "provisioners/install_ngrok.sh",
    args: "#{ngrok_authtoken} #{ngrok_exposed_port}"
end
