Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 400

  config.vm.synced_folder "./../", "/opt/vagrant"

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8085, host: 8085

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.provision "shell", path: "docker_engine.sh"
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    repo_path="/opt/vagrant"
    repo_name="bootcamp-devops-2023"
    repo_url="https://github.com/roxsross/bootcamp-devops-2023.git"
    branch="ejercicio2-dockeriza"

    apt install dos2unix -y
    find $repo_path -path "./$repo_name" -prune -type f -print0 | xargs -0 dos2unix
    chmod -R +x $repo_path
    bash $repo_path/start_services.sh $repo_path $repo_name $repo_url $branch
  SHELL
end
