Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 400

  config.vm.synced_folder "./../", "/opt/vagrant"

  config.vm.network "forwarded_port", guest: 8080, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.provision "shell", path: "docker_engine.sh"
  config.vm.provision "shell", path: "deploy_app.sh"
  config.vm.provision "shell", path: "install_ngrok.sh"
end
