Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20231011.0.0"
  config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/focal64"
  config.vm.box_check_update = true

  config.vm.boot_timeout = 900

  config.vm.synced_folder "./../", "/home/ubuntu/Exercise2"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.provision "shell", path: "docker_engine.sh", run: "always"
  config.vm.provision "shell", path: "execute_dockerfile.sh", run: "always"
end
