Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.boot_timeout = 600

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    vb.memory = 4096
    vb.cpus = 3
  end

  config.vm.provision "shell", inline: <<-SHELL
    Repo_Url="https://github.com/RecursiveDeveloper/Reto295DevOps_Exercises.git"

    cd /home/ubuntu
    git clone $Repo_Url
    cd Reto295DevOps_Exercises
    git pull origin main
    chmod -R +x ./Exercise1
    cd Exercise1/
    . ./deploy_LAMP.sh
  SHELL
end
